spring:
  application:
    name: sidecar-gateway-application

  data:
    mongodb:
      database: customer-db
      auto-index-creation: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
    restart:
      enabled: true
    info:
      enabled: true
  info:
    git:
      mode: full

